# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  api:
    build:
      context: "C:\\Projetos\\apiBozzi"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57419"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/apiBozzi.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "apibozzi:dev"
    ports:
    - "127.0.0.1:57019:57000"
    - "127.0.0.1:57219:57200"
    - "127.0.0.1:57419:57419"
    volumes:
    - "C:\\Projetos\\apiBozzi:/app:rw"
    - "C:\\Projetos\\apiBozzi:/src:rw"
    - "C:\\Users\\denno\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\denno\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.3.1\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\denno\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\denno\\AppData\\Local\\JetBrains\\Rider2025.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_12_31_13_43_16:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
